cover:
  display:
    home: false
search:
  enable: true
  service: hexo  # hexo
sidebar:
  # 主页、分类、归档等独立页面
  for_page: [blogger, category, tagcloud]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://avatars.githubusercontent.com/u/32541818?v=4
      title: TianyiGu's Blog
      subtitle:
      jinrishici: false
      social: true
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: 文章分类
        url: /categories/
    # toc:
    #   class: toc
    #   display: [desktop, mobile] # [desktop, mobile]
    #   header:
    #     icon: fas fa-list
    #     title: 本文目录
    #   list_number: false
    #   min_depth: 2
    #   max_depth: 5