cover:
  display:
    home: false
    archive: false
    others: false
search:
  enable: true
  service: hexo  # hexo
navbar:
  logo:
    img: https://cdn.jsdelivr.net/gh/serchaofan/picBed/blog/202202240150263.jpg
    icon:
    title:
pages:
  # 友链页面配置
  friends:
    layout_scheme: simple
sidebar:
  # 主页、分类、归档等独立页面
  for_page: [blogger, category, tagcloud]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://avatars.githubusercontent.com/u/32541818?v=4
      title: TianyiGu's Blog
      subtitle:
      jinrishici: false
      social: true
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: 文章分类
        url: /categories/
    # toc:
    #   class: toc
    #   display: [desktop, mobile] # [desktop, mobile]
    #   header:
    #     icon: fas fa-list
    #     title: 本文目录
    #   list_number: false
    #   min_depth: 2
    #   max_depth: 5
site_footer:
  layout: [aplayer, social, license, info, copyright]
  social:
    - icon: fab fa-github
      url: https://github.com/serchaofan
  copyright: '苏ICP备19069282号'
  br: '<br>'
article:
  body:
    top_meta: [category, date]
    bottom_meta: [tags]
    footer_widget:
      copyright:
        enable: false